FROM golang:1.20
RUN apt-get update
RUN apt install -y protobuf-compiler
RUN mkdir -p /go/src/app/microservices
RUN mkdir -p /go/src/app/microservices/common
COPY ./microservices/common /go/src/app/microservices/common/
WORKDIR /go/src/app
COPY go.mod go.sum ./
RUN go mod download
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
RUN export PATH="$PATH:$(go env GOPATH)/bin"