version: "3.3"

services:
  auth:
    environment:
      - PORT=:8390
      - PORT2=:8391
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=keyur
      - DB_PASSWORD=Test@1234
      - DB_NAME=govueadmin_users
      - ROOT_PATH=/go/src/app/microservices/auth
      - SVC_URL=host.docker.internal:8391
      - API_URL=http://host.docker.internal:8390
      - FRONTEND_APP_URL=http://govueadmin.localhost
      - SECRET_KEY=bda3b7cd3ed966b783ee846176b9eb07
      - SECRET_KEY_COOKIE=9658c83d13c479a9238355d5d792dd9b
    ports:
      - 8390:8390
      - 8391:8391

  roles:
    environment:
      - PORT=:8392
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=govueadmin_roles
      - ROOT_PATH=/go/src/app/microservices/roles
      - API_URL=http://host.docker.internal:8392
      - AUTH_SVC_URL=host.docker.internal:8391
      - FRONTEND_APP_URL=http://govueadmin.localhost
      - SECRET_KEY=bda3b7cd3ed966b783ee846176b9eb07
      - SECRET_KEY_COOKIE=9658c83d13c479a9238355d5d792dd9b
    ports:
      - 8392:8392

  users:
    environment:
      - PORT=:8399
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=govueadmin_users
      - ROOT_PATH=/go/src/app/microservices/users
      - API_URL=http://host.docker.internal:8399
      - FRONTEND_APP_URL=http://host.docker.internal.localhost
      - SECRET_KEY=bda3b7cd3ed966b783ee846176b9eb07
      - SECRET_KEY_COOKIE=9658c83d13c479a9238355d5d792dd9b
    ports:
      - 8399:8399
  
  
