version: "3.3"

services:
  auth:
    build: 
      context: .
      dockerfile: ./microservices/auth/Dockerfile
    image: app-auth:1.0
    container_name: auth-service
    volumes:
      - ./microservices/auth:/go/src/app/microservices/auth
      - ./microservices/common/feat:/go/src/app/microservices/common/feat
      - ./framework:/go/src/app/framework
      
  roles:
    build: 
      context: .
      dockerfile: ./microservices/roles/Dockerfile
    image: app-roles:1.0
    container_name: roles-service
    volumes:
      - ./microservices/roles:/go/src/app/microservices/roles
      - ./microservices/common/client/auth:/go/src/app/microservices/common/client/auth
      - ./microservices/common/feat:/go/src/app/microservices/common/feat
      - ./microservices/common/pb/auth:/go/src/app/microservices/common/pb/auth
      - ./microservices/common/middlewares/auth:/go/src/app/microservices/common/middlewares/auth
      - ./framework:/go/src/app/framework

  users:
    build: 
      context: .
      dockerfile: ./microservices/users/Dockerfile
    image: app-users:1.0
    volumes:
      - ./microservices/users:/go/src/app/microservices/users
      - ./microservices/common:/go/src/app/microservices/common
      - ./framework:/go/src/app/framework