apiVersion: v1
kind: Secret
metadata:
  name: users-microser-secret
type: Opaque
data:
  db_user: cm9vdA==
  db_password: QWRtaW5AMTIz
  secret_key: YmRhM2I3Y2QzZWQ5NjZiNzgzZWU4NDYxNzZiOWViMDc=
  secret_key_cookie: OTY1OGM4M2QxM2M0NzlhOTIzODM1NWQ1ZDc5MmRkOWI=

---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: users-microser-configmap
data:
  db_host: mongodb-service
  db_port: "27017"
  db_name: "govueadmin_users"
  root_path: "/go/src/govueadmin/microservices/users"
  api_url: "http://api.govueadmin.local"
  frontend_app_url: "http://govueadmin.localhost"
  port: ":30000"
  
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: users-pv-volume
#   labels:
#     type: local
# spec:
#   storageClassName: standard
#   capacity:
#     storage: 10Gi
#   accessModes:
#   - ReadWriteOnce
#   hostPath:
#     path: "/home/cygnet/Documents/Go_Lang_Projects/src/go_vue_admin/backend/microservices/users"

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: users-pv-claim
# spec:
#   storageClassName: standard
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 3Gi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: framework-pv-volume
#   labels:
#     type: local
# spec:
#   storageClassName: standard
#   capacity: 
#     storage: 10Gi
#   accessModes:
#   - ReadWriteOnce
#   hostPath:
#     path: "/home/cygnet/Documents/Go_Lang_Projects/src/go_vue_admin/backend/framework"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: framework-pv-claim
# spec:
#   storageClassName: standard
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microser-deployment
  labels:
    app: users-microser
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: users-microser
  template:
    metadata:
      labels:
        app: users-microser
    spec:
      volumes:
      - name: volume1
        hostPath:
          path: /mnt/go_vue_admin/go.mod
          type: File
      - name: volume2
        hostPath:
          path: /mnt/go_vue_admin/go.sum
          type: File
      - name: volume3
        hostPath:
          path: /mnt/go_vue_admin/framework
          type: Directory
      - name: volume4
        hostPath:
          path: /mnt/go_vue_admin/microservices/users
          type: Directory
      - name: volume5
        hostPath:
          path: /mnt/go_vue_admin/microservices/users/main.go
          type: File
      - name: volume6
        hostPath:
          path: /mnt/go_vue_admin/microservices/users/.air.toml
          type: File
      - name: volume7
        hostPath:
          path: /mnt/go_vue_admin/microservices/users/build.sh
          type: File
      containers:
      - name: users-microser
        image: govueadmin-users:2.3
        #workingDir: /go/src/govueadmin/microservices/users
        #command: 
        #- "./build.sh"
        volumeMounts:
        - name: volume1
          mountPath: /go/src/govueadmin/go.mod
        - name: volume2
          mountPath: /go/src/govueadmin/go.sum
        - name: volume3
          mountPath: /go/src/govueadmin/framework
        - name: volume4
          mountPath: /go/src/govueadmin/microservices/users
        - name: volume5
          mountPath: /go/src/govueadmin/microservices/users/main.go
        - name: volume6
          mountPath: /go/src/govueadmin/.air.toml
        - name: volume7
          mountPath: /go/src/govueadmi/build.sh
        ports:
        - containerPort: 30000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: users-microser-configmap
              key: port
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: users-microser-configmap
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: users-microser-configmap
              key: db_port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: users-microser-secret
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: users-microser-secret
              key: db_password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: users-microser-configmap
              key: db_name
        - name: ROOT_PATH
          valueFrom:
            configMapKeyRef:
              name: users-microser-configmap
              key: root_path
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: users-microser-configmap
              key: api_url
        - name: FRONTEND_APP_URL
          valueFrom:
            configMapKeyRef:
              name: users-microser-configmap
              key: frontend_app_url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: users-microser-secret
              key: secret_key
        - name: SECRET_KEY_COOKIE
          valueFrom:
            secretKeyRef:
              name: users-microser-secret
              key: secret_key_cookie
---
apiVersion: v1
kind: Service
metadata:
  name: users-microser-service
spec:
  selector:
    app: users-microser
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 30000
    targetPort: 30000
    nodePort: 30000